- .github/workflows/codeql-analysis.yml
@mollybsmith-noaa - I was reviewing GitHub's CodeQL tool and realized it added itself to the `main` branch instead of to `development`. Are you okay with me merging this change from `main` into `development` or would you like me to add a commit reverting this change in `main` and then create a PR off of the `development` branch for this?
I think merging into development is the most straightforward. However, either way will work well and neither is hard. It's mostly a matter of preference.
> Set up GitHub Code Scanning

- .github/workflows/prune-pr-images.yml
Using expression syntax in just part of the if statement was causing the RHS of the if to not evaluate. Double quotes are also not allowed in if statements at this time.
> Fix the PR image pruning job

- .github/workflows/build.yml
This will add a date string like: `2022-02-07.09:01:42.+0000` to the version string.
> Add commit date to version string

- .github/workflows/deploy.yml
Bring the fix for the deploy action syntax from #721 to main.
> Fix deploy action syntax

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/project.md
- .github/ISSUE_TEMPLATE/task.md
- .github/workflows/add-issue-to-project.yml
This commit adds issue templates for our common issue types as well as a
CI job to add newly created issues to the project board.
> Setup repo to work with new project board

- apps/surface/server/dataFunctions/data_map.js
- apps/upperair/server/dataFunctions/data_map.js
MATS component of pull request to add legends to scalar map plots.
> Added legend onto map plots.

- apps/cb-ceiling/server/dataFunctions/data_map.js
- apps/ceil-vis/server/dataFunctions/data_map.js
- apps/ceil-vis15/server/dataFunctions/data_map.js
- apps/surface/server/dataFunctions/data_map.js
- apps/upperair/server/dataFunctions/data_map.js
I've improved the color schemes, marker sizes, and legend text on our surface/upperair maps, and the color scheme and legend text on our ceiling/visibility maps. This pull request links to the appropriate MATScommon code changes.
> Feature map colors

- apps/precipGauge/server/main.js
- apps/precipitation1hr/server/main.js
- apps/ptype/server/dataFunctions/data_contour.js
- apps/ptype/server/dataFunctions/data_contour_diff.js
- apps/ptype/server/dataFunctions/data_dailymodelcycle.js
- apps/ptype/server/dataFunctions/data_dieoff.js
- apps/ptype/server/dataFunctions/data_histogram.js
- apps/ptype/server/dataFunctions/data_series.js
- apps/ptype/server/dataFunctions/data_validtime.js
- apps/ptype/server/main.js
This pull request contains my API for getting scorecard metadata from individual apps. It uses server-side routes which are in the linked matsMethods.js commits. Documentation fo the API is at https://docs.google.com/document/d/1nX_hB0P9VyUokSYxWwtHwmB6MrTtklX0ZFlgOUtkyEg/edit?usp=sharing
> Feature selector api

- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/project.md
Update the `project.md` template to use the new epic and 'needs requirements' labels
> Update the issue templates to use the new labels

- .github/README.md
- README.md
Ideally, this will help onboard folks who are new to Docker & GitHub Actions.
> Add documentation for our CI process

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/deploy.yml
These changes bring #863 to `main` so that they're picked up by Dependabot
> Dependabot fixes cp

- .eslintrc.json
- .prettierrc
- apps/scorecard/.meteor/versions
- apps/scorecard/app.css
I believe that should have a PR to merge this scorecard work into development. It has a couple more changes.
> Scorecard display

- apps/anomalycor/server/main.js
- apps/ceil-vis/server/main.js
- apps/ceil-vis15/server/main.js
- apps/landuse/server/main.js
- apps/precipAccum/server/main.js
- apps/precipGauge/server/main.js
- apps/precipitation1hr/server/main.js
- apps/ptype/server/main.js
- apps/radar/server/main.js
- apps/surface/server/main.js
- apps/surfrad/server/main.js
- apps/upperair/server/main.js
> Added a couchbase connection to all MATS apps so the scorecard plot windows will work

- apps/anomalycor/server/dataFunctions/data_contour.js
- apps/anomalycor/server/dataFunctions/data_contour_diff.js
- apps/anomalycor/server/dataFunctions/data_dieoff.js
- apps/anomalycor/server/dataFunctions/data_histogram.js
- apps/anomalycor/server/dataFunctions/data_profile.js
- apps/anomalycor/server/dataFunctions/data_series.js
- apps/scorecard/app.css
- apps/scorecard/server/dataFunctions/processScorecard.js
- apps/scorecard/server/main.js
As far as I can tell everything works in this PR. We'll probably find oddities later, but I'd like to merge to development for more extensive testing, especially with the pop-out windows. This PR does change the data structure in the scorecards, so it's probable that old scorecards saved in couchbase won't work anymore.
> Add other apps to scorecard

- apps/scorecard/server/dataFunctions/processScorecard.js
This PR renames scorecard rows as acorecard blocks.
> Replaced scorecard "row" with "block"

- apps/scorecard/server/dataFunctions/sqlTemplates/tmpl_landuse_timeseries.sql
- apps/scorecard/server/main.js
This PR adds in scorecard support for the landuse app and excludes stats that don't make sense on a scorecard
> Add landuse to and exclude stats from scorecards

- apps/scorecard/server/dataFunctions/processScorecard.js
Scorecards are now initialized with fill values and display them as white (like the background)
> Scorecard fill values

- apps/scorecard/server/dataFunctions/sqlTemplates/tmpl_precipAccum_timeseries.sql
- apps/scorecard/server/dataFunctions/sqlTemplates/tmpl_precipitation1hr_timeseries.sql
- apps/scorecard/server/dataFunctions/sqlTemplates/tmpl_radar_timeseries.sql
This commit fixes the scorecard queries for precipAccum, radar, and precipitation1hr
> fixed scorecard queries

- apps/scorecard/package-lock.json
- apps/scorecard/server/dataFunctions/processScorecard.js
- apps/upperair/package-lock.json
- apps/upperair/package.json
This PR does two things. First it implements durability options for the upsert to couchbase and uses the durabilitiy MAJORITY_AND_PERSIST_TO_ACTIVE to ensure that the scorecard document is fully persisted before moving on to the status page (and notifying the vxDataProcessor) and Second it uses scanconsistency on the query for scorecardinfo and scorecarddata.
> 959-make-sure-scorecard-documents-are-fully-persisted-prior-to-notifying-the-vxdataprocessor-to-process-the-scorecard

- .github/workflows/build.yml
- apps/cb-ceiling/.eslintrc.json
- apps/cb-ceiling/app.css
- apps/cb-ceiling/client/main.js
- apps/cb-ceiling/server/dataFunctions/data_contour.js
- apps/cb-ceiling/server/dataFunctions/data_contour_diff.js
- apps/cb-ceiling/server/dataFunctions/data_dailymodelcycle.js
- apps/cb-ceiling/server/dataFunctions/data_dieoff.js
- apps/cb-ceiling/server/dataFunctions/data_histogram.js
- apps/cb-ceiling/server/dataFunctions/data_map.js
- apps/cb-ceiling/server/dataFunctions/data_perfDiagram.js
- apps/cb-ceiling/server/dataFunctions/data_series.js
- apps/cb-ceiling/server/dataFunctions/data_threshold.js
- apps/cb-ceiling/server/dataFunctions/data_validtime.js
- apps/cb-ceiling/server/main.js
- apps/cb-ceiling/test/cbQueryTests/__tests__/queryTests0.js
- apps/cb-ceiling/test/cbQueryTests/config/config.json
- apps/cb-ceiling/test/cbQueryTests/jest.config.json
Finish the work started in #884 to transition the MATS apps to be formatted by Prettier and linted by Eslint. 
Closes #896
> Apply linting to cb ceiling

- kubernetes/base/ensemble/deployment.yaml
- kubernetes/base/ensemble/kustomization.yaml
- kubernetes/base/ensemble/service.yaml
- kubernetes/overlays/gsl-dev/ensemble/deployment.yaml
- kubernetes/overlays/gsl-dev/ensemble/kustomization.yaml
- kubernetes/overlays/gsl-dev/ingress-apps.yaml
- kubernetes/overlays/gsl-dev/kustomization.yaml
Add base & dev cluster overlay manifests for the ensemble app.
Closes #1056
> Add Kubernetes manifests for the ensemble app

- apps/cb-metar/server/dataFunctions/data_contour.js
- apps/cb-metar/server/dataFunctions/data_contour_diff.js
- apps/cb-metar/server/dataFunctions/data_dailymodelcycle.js
- apps/cb-metar/server/dataFunctions/data_dieoff.js
- apps/cb-metar/server/dataFunctions/data_histogram.js
- apps/cb-metar/server/dataFunctions/data_map.js
- apps/cb-metar/server/dataFunctions/data_series.js
- apps/cb-metar/server/dataFunctions/data_threshold.js
- apps/cb-metar/server/dataFunctions/data_validtime.js
- apps/cb-metar/server/dataFunctions/sqlTemplates/tmpl_CTC.sql
- apps/cb-metar/server/dataFunctions/sqlTemplates/tmpl_PartialSums.sql
- apps/cb-metar/server/main.js
- apps/ceil-vis/server/dataFunctions/data_map.js
- apps/ceil-vis15/server/dataFunctions/data_map.js
This PR adds the ability to filter on a single obs and a single model discriminator value range.
> Add filtering to cb-metar

- .github/dependabot.yml
Reduce the frequency of Dependabot version updates from weekly to monthly.
> Reduce frequency of Dependabot updates

- apps/surfrad/server/dataFunctions/data_contour.js
- apps/surfrad/server/dataFunctions/data_contour_diff.js
- apps/surfrad/server/dataFunctions/data_dailymodelcycle.js
- apps/surfrad/server/dataFunctions/data_dieoff.js
- apps/surfrad/server/dataFunctions/data_histogram.js
- apps/surfrad/server/dataFunctions/data_map.js
- apps/surfrad/server/dataFunctions/data_series.js
- apps/surfrad/server/dataFunctions/data_simple_scatter.js
- apps/surfrad/server/dataFunctions/data_validtime.js
- apps/surfrad/server/main.js
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/make_regions_per_model_mats_all_categories_surfrad_avg.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/run_mats_metadata_pt1.tcsh
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/run_mats_metadata_pt2.tcsh
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/run_mats_metadata_pt3.tcsh
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/run_mats_metadata_pt4.tcsh
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/run_mats_metadata_pt5.tcsh
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_surfrad_avg.py
- tests/src/features/surfrad/basic/addRemoveMap.feature
This PR adds the ability to view time-averaged data in the surfrad app, and also adds map plots to that app.
> Feature surfrad upgrades

- home/static/css/home.css
This PR fixes a couple of things that came up during testing our 6.0.0 release
> Feature v6.0.0 fixes

- scripts/matsMetaDataForApps/createMetaData/mysql/mats/make_regions_per_model_mats_all_categories_aircraft.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_aircraft.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_aircraft_prepbufr.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_ceiling.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_ceiling5.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_cloud_base.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_cref.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_echotop.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_precip.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_precip2.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_precip_1hr.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_precip_gauge.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_surface.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_surfrad.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_surfrad_avg.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_upperair.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_upperair2.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_upperair_prepbufr.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_vgtyp.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_vil.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_visibility.py
- scripts/matsMetaDataForApps/createMetaData/mysql/mats/update_metadata_visibility1.py
Adding pointers to conda environment 3_6 for the individual update scripts
> updating the python environment to point to conda avid_verify_py3_6

- apps/cb-metar/package-lock.json
- apps/ceil-vis/package-lock.json
- apps/ceil-vis15/package-lock.json
- apps/ensemble/package-lock.json
- apps/landuse/package-lock.json
- apps/precipAccum/package-lock.json
- apps/precipGauge/package-lock.json
- apps/precipitation1hr/package-lock.json
- apps/ptype/package-lock.json
- apps/radar/package-lock.json
- apps/scorecard/package-lock.json
- apps/surface/package-lock.json
- apps/surfrad/package-lock.json
- apps/upperair/package-lock.json
> Removed meteor-node-stubs and updated
