- .github/workflows/codeql-analysis.yml
- .github/workflows/trivy-code-analysis.yml
Add Trivy repo scanning to CI to detect node.js dependency vulnerabilities. We still need to add container checks. However, that will need to wait until we are able to build the containers with GitHub Actions.
Closes #633
> Add Trivy repo scanning to CI

- .github/workflows/build.yml
GitHub support recommends we decrease our job timeout to speed up feedback on stuck builds. Our jobs should only take 10 minutes so 20 minutes seems reasonable.
Closes #658
> Reduce our job timeout from 6 hours to 20 min

- Dockerfile
Update our Dockerfile to fix CI breakages.
* Update base image to use Meteor 2.5 - matching the application version
* Explicitly build the native dependencies
Closes #680
> Fix GitHub CI

- Dockerfile
Add a `debug` stage that can be targeted with `docker build --target debug ...` to make debugging easier.
Closes #682
> Create stage for container debugging

- .github/workflows/build.yml
Trivy was pinned to 0.0.20 which wasn't compatible with alpine 3.15 and
was silently failing.
> Use the latest version of Trivy in CI

- .dockerignore
- Dockerfile
Force a rebuild of the mats-common dependencies
The mats-common Meteor Atmosphere package installs some native
dependencies in the first stage of this Dockerfile. That stage uses a
Ubuntu base image so causes problems when we switch to the
musl-based Alpine production image. We need to 'npm rebuild' in the
meteor package's node_modules as well as the places the
'build-meteor-npm-dependencies.sh' script does it.
Closes #689
> Support the couchbase SDK in docker

- .dockerignore
.dockerignore files follow Go's filepath.Match rules which is not
similar to how .gitignore files work. We need to use the ** glob
expansion to match subdirectories.
> Fix the syntax for .dockerignore

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Remove the ability for the "Build" workflow to push to the
production image registry. Create a new workflow that copies
tagged images from the dev registry to the production registry
when a GitHub Release is created.
> Add a workflow to control which apps are released

- .github/workflows/prune-untagged-images.yml
The upstream GH Action had an unpinned dependency change and broke the action. This was fixed in 1.4.1 by pinning their dependencies. https://github.com/snok/container-retention-policy/releases/tag/v1.4.1
> Fix untagged image cleanup

- .github/workflows/deploy.yml
The `${GITHUB_REF}` statements aren't a GitHub Actions context - they're an env variable.
This is the MATS counterpart to: https://github.com/dtcenter/METexpress/pull/81
> Fix the deploy action

- .github/workflows/deploy.yml
Whitespace isn't valid in an `${ENV}` block. Also, remove the leading `refs/tags/` as we don't want that in our image tags.
This was tested in a sandbox repo here: https://github.com/ian-noaa/github-actions-playground/runs/5879432800?check_suite_focus=true with the following GitHub Actions file: https://github.com/ian-noaa/github-actions-playground/blob/dc29529916f73937d33e562097801f79eb7522ab/.github/workflows/test-syntax.yml
The results from the test show that the whitespace was the issue and that using syntax like: `${GITHUB_REF:/refs/tags/}` is valid and will trim the extra parts of the ref we don't want in our image tags.
> Fix deploy action syntax

- Dockerfile
mongodb-tools isn't needed in the production image - it consists
of CLI utilities for working with mongo databases which the app
doesn't need to do.
> Update node image version and remove mongodb-tools

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/trivy-code-analysis.yml
CodeQL v1 is being deprecated December 2022 according to GitHub's blog.
Switch to v2 to get ahead of the deprecation.
> Bump CodeQL to v2

- apps/landuse/server/main.js
- apps/surface/server/main.js
Fix for a bug Tanya found where surface retros would not plot matched, because they apparently have even fewer partial sums available than realtime models. Queries have been adjusted accordingly.
> Fixed bug where surface retros would not plot matched.

- .github/workflows/stale.yml
The team wanted issues and PRs to be marked as stale after 90 days and didn't want issues or PRs to be automatically closed.
Closes #832
> Add a CI job to label stale issues

- .github/dependabot.yml
Currently, only use [Dependabot on GitHub Actions (GHA)](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot). If we want, we can turn Dependabot on for npm in the future.
> Turn on dependabot for GHA

- .github/dependabot.yml
Currently, only use Dependabot on GitHub Actions (GHA). If we want, we can turn Dependabot on for npm in the future.
> Turn on dependabot for GitHub Actions (#853)

- kubernetes/base/mongo/pvc.yaml
Randy mentioned that we typically use 10 GB of space for mongo. Having this extra space will be especially important for the scorecard app.
Closes #890
> K8s PR 4 - Increase monogo pvc size

- apps/scorecard/server/dataFunctions/processScorecard.js
- apps/scorecard/server/dataFunctions/sqlTemplates/tmpl_upperair_timeseries.sql
In this PR, 
- Upper air queries work now. They were broken because most of the RAOB tables don't have the full set of partial sums, so a `JOIN` is sadly necessary.
- I fixed a bug that Gopa found where `Infinity` was being treated as a string rather than a number.
- The scorecard status page now waits to appear until the submitted scorecard is processed.
> Assorted bug fixes

- .github/workflows/build.yml
- Dockerfile
Switch our Dockerfile to use `node:14-bullseye-slim` instead of `node:14-alpine` for our production image. Switching to a Debian-based OS makes CI builds much quicker (builds take ~15 min instead of 90+ min) and removes a whole host of libc/musl compatibility issues that come about from using the Debian-based `meteor-base` image and copying artifacts into an Alpine-based production image. 
Additionally, I took the opportunity to:
- add a step at the end of our Dockerfile to pull in OS updates to mitigate OS vulnerabilities. 
- eliminate the `mariadb` package. This will save space and cut down on vulnerabilities. MATS uses pure-Python and pure-JS MySQL dependencies and has no need for a native mysql/mariadb package to be installed. Additionally, we didn't need to have a whole mariadb …
> Switch to a Debian-based image for production 

- Dockerfile
We were previously installing OS-vendored versions of our Python dependencies as that was easiest when on Alpine and dealing with `musl`. We're now on a Debian-base image so `pip` packages will be well-tested, compatible, and more up-to-date than the OS-vendored ones.
I also added `g++` and `build-essentials` to the image to support ARM/Apple Silicon builds.
> Update container image to address vulnerabilities

- Dockerfile
- apps/cb-ceiling/package-lock.json
- apps/cb-ceiling/package.json
This PR does two things:
1. Removes some unused statements in our `Dockerfile`
2. Updates the Node Couchbase SDK to v4.2.5
These two changes shrink our container image's size from 1.15 GB to ~740 MB.
> Reduce container image size

- apps/ensemble/server/dataFunctions/data_contour.js
- apps/ensemble/server/dataFunctions/data_contour_diff.js
- apps/ensemble/server/dataFunctions/data_dieoff.js
- apps/ensemble/server/dataFunctions/data_histogram.js
- apps/ensemble/server/dataFunctions/data_series.js
- apps/ensemble/server/dataFunctions/data_threshold.js
- apps/ensemble/server/dataFunctions/data_validtime.js
- apps/ensemble/server/main.js
The GSL ensemble app now handles plot type the way that METexpress does, because statistic needs to be a dependent of plot type.
> Fixed bug that caused some selectors to remain hidden

- home/README.md
- home/main.go
- home/templates/header.html
- home/templates/index.html
- home/templates/navbar.html
- home/templates/toggles.html
The "Environment" config option had two effects - it set the subtitle on the page if it was anything other than "Production" and also would show/hide the toggle for experimental GSL apps if it was set to "Production". This overloading was undesired and so I've created a new "EnvironmentLabel" option to control the subtitle in the UI and a "IsProduction" option to toggle show/hide behavior.
> Split the Environment config into two options

- home/README.md
- home/main.go
- home/templates/alert.html
- home/templates/index.html
Add the ability to display a bootstrap 5 alert to convey shutdown information to users. The alert visibility and message are controlled via the config file.
> Add a configurable alert to convey shutdown info

- apps/cb-metar/server/dataFunctions/data_contour.js
- apps/cb-metar/server/dataFunctions/data_contour_diff.js
- apps/cb-metar/server/dataFunctions/data_dailymodelcycle.js
- apps/cb-metar/server/dataFunctions/data_dieoff.js
- apps/cb-metar/server/dataFunctions/data_histogram.js
- apps/cb-metar/server/dataFunctions/data_map.js
- apps/cb-metar/server/dataFunctions/data_series.js
- apps/cb-metar/server/dataFunctions/data_validtime.js
- apps/cb-metar/server/main.js
This PR switches the METAR app to use Gopa's new metadata, and hopefully fixes a persistent date bug.
> New metadata

- kubernetes/overlays/aws-dev/cb-metar/deployment.yaml
- kubernetes/overlays/aws-dev/cb-metar/kustomization.yaml
- kubernetes/overlays/aws-dev/home/deployment.yaml
- kubernetes/overlays/aws-dev/home/kustomization.yaml
- kubernetes/overlays/aws-dev/ingress-apps.yaml
- kubernetes/overlays/aws-dev/ingress-home.yaml
- kubernetes/overlays/aws-dev/kustomization.yaml
- kubernetes/overlays/aws-dev/mongo/delete-pvc.yaml
- kubernetes/overlays/aws-dev/mongo/deployment.yaml
- kubernetes/overlays/aws-dev/mongo/kustomization.yaml
- kubernetes/overlays/aws-dev/mongo/mongod.conf
- kubernetes/overlays/gsl-dev/ingress-apps.yaml
This change:
- updates the gsl-dev cluster manifests to match the URLs actually in use
- adds the initial Kustomize overlays to deploy cb-metar to an EKS cluster
I ended up needing to disable the PVC for mongo in EKS as we don't yet have a CSI driver in the cluster. I also disabled resource requests & limits for all our deployments so that we could do some performance testing/tuning.
> Deploy MATS to EKS

- apps/upperair/server/dataFunctions/data_dailymodelcycle.js
- apps/upperair/server/dataFunctions/data_dieoff.js
- apps/upperair/server/dataFunctions/data_histogram.js
- apps/upperair/server/dataFunctions/data_map.js
- apps/upperair/server/dataFunctions/data_profile.js
- apps/upperair/server/dataFunctions/data_series.js
- apps/upperair/server/dataFunctions/data_validtime.js
Our upper air app was trying to interpolate levels with `ceil((m0.press-20)/50)*50` instead of `ceil((m0.press-25)/50)*50`, which would have caused our levels on the graph to be slightly off.
> Fixed upperair level interpolation bug

- apps/upperair/server/dataFunctions/data_contour.js
- apps/upperair/server/dataFunctions/data_contour_diff.js
- apps/upperair/server/dataFunctions/data_dailymodelcycle.js
- apps/upperair/server/dataFunctions/data_dieoff.js
- apps/upperair/server/dataFunctions/data_histogram.js
- apps/upperair/server/dataFunctions/data_profile.js
- apps/upperair/server/dataFunctions/data_series.js
- apps/upperair/server/dataFunctions/data_simple_scatter.js
- apps/upperair/server/dataFunctions/data_validtime.js
Most of our upper air RAOB tables need to be joined with the GFS or other models to fill in missing obs sums. However, this is unnecessary for the lab's primary models. This PR excludes those models.
> Don't join main GSL models with other tables

- .github/workflows/build-mats.yml
- Dockerfile
Updates CI & our container image for Meteor 3. Key changes:
* Update the Docker Meteor image used in the Dockerfile to match the version of Meteor we're updating the code to
* Update various Docker Node images to Node 22
* Install our runtime Python dependencies in a virtual environment
> Update container & CI for Meteor 3
